#
# Device makefile for Samsung Galaxy C7 (SM-C7000 / c7ltechn) — LineageOS 16.0
#
# Layout notes:
#  - Non-Treble: NO vendor partition. /vendor -> /system/vendor (symlink created by
#    the ramdisk init.rc). All "vendor" destinations below therefore use
#    $(TARGET_COPY_OUT_SYSTEM)/vendor/... so blobs land inside system.img.
#  - HAL services and their .rc files ship as prebuilt blobs from the stock
#    firmware (see vendor/samsung/c7ltechn) and are started by init via
#    /vendor/etc/init/*.rc + /vendor/etc/init/hw/init.qcom.rc.
#

# Inherit vendor blobs (generated by tools/gen-vendor-mk.py)
$(call inherit-product-if-exists, vendor/samsung/c7ltechn/c7ltechn-vendor.mk)

DEVICE_PATH := device/samsung/c7ltechn

# Overlays
DEVICE_PACKAGE_OVERLAYS += \
    $(DEVICE_PATH)/overlay

# System properties
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop

# Screen (C7: 5.7" 1080p, 420 dpi)
PRODUCT_AAPT_CONFIG := normal
PRODUCT_AAPT_PREF_CONFIG := xxhdpi
TARGET_SCREEN_HEIGHT := 1920
TARGET_SCREEN_WIDTH := 1080

# Hardware feature permissions -> /system/vendor/etc/permissions
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.bluetooth_le.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.bluetooth_le.xml \
    frameworks/native/data/etc/android.hardware.bluetooth.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.bluetooth.xml \
    frameworks/native/data/etc/android.hardware.camera.flash-autofocus.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    frameworks/native/data/etc/android.hardware.camera.front.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.camera.front.xml \
    frameworks/native/data/etc/android.hardware.location.gps.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.location.gps.xml \
    frameworks/native/data/etc/android.hardware.opengles.aep.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.opengles.aep.xml \
    frameworks/native/data/etc/android.hardware.sensor.accelerometer.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.sensor.accelerometer.xml \
    frameworks/native/data/etc/android.hardware.sensor.compass.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.sensor.compass.xml \
    frameworks/native/data/etc/android.hardware.sensor.gyroscope.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.sensor.gyroscope.xml \
    frameworks/native/data/etc/android.hardware.sensor.light.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.sensor.light.xml \
    frameworks/native/data/etc/android.hardware.sensor.proximity.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.sensor.proximity.xml \
    frameworks/native/data/etc/android.hardware.telephony.gsm.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.telephony.gsm.xml \
    frameworks/native/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
    frameworks/native/data/etc/android.hardware.usb.accessory.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.usb.accessory.xml \
    frameworks/native/data/etc/android.hardware.usb.host.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.usb.host.xml \
    frameworks/native/data/etc/android.hardware.vulkan.level-0.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.vulkan.level-0.xml \
    frameworks/native/data/etc/android.hardware.vulkan.version-1_0_3.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.vulkan.version-1_0_3.xml \
    frameworks/native/data/etc/android.hardware.wifi.direct.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.wifi.direct.xml \
    frameworks/native/data/etc/android.hardware.wifi.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.hardware.wifi.xml \
    frameworks/native/data/etc/android.software.midi.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.software.midi.xml \
    frameworks/native/data/etc/android.software.sip.voip.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/android.software.sip.voip.xml \
    frameworks/native/data/etc/handheld_core_hardware.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/permissions/handheld_core_hardware.xml

# Rootdir: fstab + vendor init scripts (stock, from C7000ZCS3CRJ1)
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/rootdir/fstab.qcom:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/fstab.qcom \
    $(DEVICE_PATH)/rootdir/init.qcom.rc:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/init/hw/init.qcom.rc \
    $(DEVICE_PATH)/rootdir/init.target.rc:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/init/hw/init.target.rc \
    $(DEVICE_PATH)/rootdir/init.carrier.rc:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/init/hw/init.carrier.rc \
    $(DEVICE_PATH)/rootdir/init.qcom.usb.rc:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/init/hw/init.qcom.usb.rc \
    $(DEVICE_PATH)/rootdir/init.msm.usb.configfs.rc:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/init/hw/init.msm.usb.configfs.rc \
    $(DEVICE_PATH)/rootdir/init.qcom.factory.rc:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/init/hw/init.qcom.factory.rc \
    $(DEVICE_PATH)/rootdir/init.qcom.test.rc:$(TARGET_COPY_OUT_SYSTEM)/vendor/etc/init/hw/init.qcom.test.rc

# VINTF manifests
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/configs/manifest.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/manifest.xml \
    $(DEVICE_PATH)/configs/compatibility_matrix.xml:$(TARGET_COPY_OUT_SYSTEM)/compatibility_matrix.xml \
    $(DEVICE_PATH)/configs/framework_manifest.xml:$(TARGET_COPY_OUT_SYSTEM)/vendor/framework_manifest.xml

# AOSP-built HAL services (impl libs come from vendor blobs; the matching
# stock service binaries are excluded from the blob list to avoid duplicates)
PRODUCT_PACKAGES += \
    android.hardware.audio@2.0-service \
    android.hardware.health@1.0-service \
    android.hardware.light@2.0-service \
    android.hardware.power@1.0-service \
    android.hardware.thermal@1.0-service \
    android.hardware.usb@1.0-service \
    libaudio-resampler \
    libaudioroute \
    libtinycompress \
    tinymix \
    libion

# Keep the boot animation for 1080p
PRODUCT_BOOTANIMATION := 1080p
