#!/usr/bin/env python3
"""
gen-vendor-mk.py — generate vendor/samsung/c7ltechn/c7ltechn-vendor.mk
from the committed blob tree vendor/samsung/c7ltechn/proprietary/.

The C7 is non-Treble: there is NO vendor partition; /vendor is a symlink
to /system/vendor. All blobs are therefore installed under the SYSTEM
image at /system/vendor/... (dest prefix system/vendor/...).

Blobs that LineageOS 16.0 builds from AOSP source are excluded (the AOSP
binary is used instead) to avoid duplicate install paths:
  - HAL service binaries listed in EXCLUDED_SERVICES
  - their init .rc files under vendor/etc/init/

Symlinks: their CONTENT is copied (make dereferences); if the link target
does not exist inside the blob tree the entry is skipped.
"""

import os
import re
import sys

VENDOR_ROOT = "vendor/samsung/c7ltechn"
PROPRIETARY = os.path.join(VENDOR_ROOT, "proprietary")

# Service binaries that LineageOS 16.0 builds from AOSP source.
# (The matching stock binaries and their .rc files are NOT copied.)
EXCLUDED_SERVICES = [
    "android.hardware.audio@2.0-service",
    "android.hardware.health@1.0-service",
    "android.hardware.light@2.0-service",
    "android.hardware.power@1.0-service",
    "android.hardware.thermal@1.0-service",
    "android.hardware.usb@1.0-service32",
    "android.hardware.usb@1.0-service64",
]

def excluded_rel(rel):
    """rel is like 'vendor/bin/hw/xxx' or 'system/...'"""
    if rel.startswith("vendor/bin/hw/"):
        name = os.path.basename(rel)
        if name in EXCLUDED_SERVICES:
            return True
    if rel.startswith("vendor/etc/init/"):
        base = os.path.basename(rel)
        stem = re.sub(r"\.rc$", "", base)
        if stem in EXCLUDED_SERVICES:
            return True
    return False

def entries():
    out = []
    for root, dirs, files in os.walk(PROPRIETARY):
        for f in files:
            p = os.path.join(root, f)
            rel = os.path.relpath(p, PROPRIETARY)  # vendor/... or system/...
            if excluded_rel(rel):
                continue
            if os.path.islink(p):
                tgt = os.readlink(p)
                resolved = os.path.normpath(os.path.join(os.path.dirname(p), tgt))
                exists = os.path.exists(resolved) or os.path.islink(resolved)
                out.append((rel, True, exists, tgt))
            else:
                out.append((rel, False, True, None))
    out.sort()
    return out

def dest_for(rel):
    if rel.startswith("vendor/"):
        return "$(TARGET_COPY_OUT_SYSTEM)/vendor/" + rel[len("vendor/"):]
    if rel.startswith("system/"):
        return "$(TARGET_COPY_OUT_SYSTEM)/" + rel[len("system/"):]
    return "$(TARGET_COPY_OUT_SYSTEM)/" + rel

def main():
    if not os.path.isdir(PROPRIETARY):
        print("No blob tree at %s" % PROPRIETARY, file=sys.stderr)
        sys.exit(1)
    items = entries()
    copied = [(r, t) for r, _, ok, t in items if ok]
    symlinks = [(r, t) for r, _, ok, t in items if not ok]
    lines = []
    lines.append("# Auto-generated by tools/gen-vendor-mk.py — do not edit.")
    lines.append("# Samsung Galaxy C7 (SM-C7000 / c7ltechn) — LineageOS 16.0")
    lines.append("# Non-Treble: blobs install under system.img at /system/vendor")
    lines.append("")
    lines.append("PRODUCT_COPY_FILES += \\")
    for i, (rel, _t) in enumerate(copied):
        sep = " \\" if i < len(copied) - 1 else ""
        lines.append("    %s/%s:%s%s" % (PROPRIETARY, rel, dest_for(rel), sep))
    lines.append("")
    # Recreate absolute symlinks (targets only resolve on-device at /system/vendor)
    for rel, tgt in symlinks:
        dest = dest_for(rel)
        d = os.path.dirname(dest)
        lines.append("$(shell mkdir -p %s && ln -sfn %s %s)" % (d, tgt, dest))
    lines.append("")
    lines.append("# %d blob entries copied; %d absolute symlinks recreated at build time" % (
        len(copied), len(symlinks)))
    with open(os.path.join(VENDOR_ROOT, "c7ltechn-vendor.mk"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("Wrote %s: %d copy entries, %d symlink rules" % (
        os.path.join(VENDOR_ROOT, "c7ltechn-vendor.mk"), len(copied), len(symlinks)))

if __name__ == "__main__":
    main()
